name: Release

on:
  push:
    branches:
      - main
      - dev

jobs:
  release:
    concurrency: refs/notes/semantic-release
    name: Release App
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed to write releases
    outputs:
      version: ${{ steps.appVersion.outputs.appVersion }}
    if: |
      (github.repository == 'sefaria/sefaria-mcp')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch entire history. Required for chart-releaser; see https://github.com/helm/chart-releaser-action/issues/13#issuecomment-602063896
          fetch-depth: 0
      - name: fetch head of branch to ensure semantic can run
        run: git pull origin $GITHUB_REF
      - name: Download yq
        run: |
          wget -nv -nc -O yq https://github.com/mikefarah/yq/releases/download/v4.20.2/yq_linux_amd64
          chmod +x yq
          echo "$PWD" >> $GITHUB_PATH
      - uses: cycjimmy/semantic-release-action@v4
        id: semantic
        with:
          working_directory: ./
          semantic_version: 18.0.1
          extra_plugins: |
            conventional-changelog-conventionalcommits@6.1.0
            @semantic-release/exec@6.0.3
            @semantic-release/git@10.0.1
            @semantic-release/commit-analyzer@9.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: check version was generated
        id: appVersion
        run: |
          if [[ -z "${{ steps.semantic.outputs.new_release_version }}" ]]; then
            if [[ -z "$(git tag --points-at HEAD -l 'v*')" ]]; then
              echo "No release version available"
              exit 1
            else
            echo "appVersion=$(git tag --points-at HEAD -l 'v*')" >> $GITHUB_OUTPUT
            fi
          else
            echo "appVersion=${{ steps.semantic.outputs.new_release_version }}" >> $GITHUB_OUTPUT
          fi
      - name: "Version Info:"
        run: echo "${{ steps.appVersion.outputs.appVersion }}"
  build:
    runs-on: ubuntu-latest
    needs: release
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.release.output.version }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/${{ secrets.GKE_PROJECT_ID}}/locations/global/workloadIdentityPools/github/providers/github'
          service_account: '${{ secrets.GKE_SA }}'
      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: us-docker.pkg.dev
          username: oauth2accesstoken
          password: '${{ steps.auth.outputs.access_token }}'
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT
      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            us-docker.pkg.dev/${{ secrets.GKE_PROJECT }}/container/sefaria-mcp
          tags: |
            type=ref,event=tag
            type=sha,enable=true,priority=100,prefix=sha-,suffix=-${{ steps.date.outputs.date }},format=short
            type=sha
            type=semver,pattern={{raw}},value=${{ needs.release.outputs.version}}
          flavor: |
            latest=true
      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            TYPE=build-prod
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Deploy
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" \
          https://api.github.com/repos/Sefaria/AppliedAI-Infrastructure/actions/workflows/mcp-deploy.yml/dispatches \
          -d '{"ref":"main", "inputs": { "environment": "${{ contains(github.ref, 'main') && 'prod' || 'dev' }}", "appVersion": "${{ needs.release.outputs.version}}", "appName": "mcp" }}'
